In [1]:
import torch
from d2l import torch as d2l

In [2]:
# 创建一个 4x6 的张量 (4行, 6列)
A = torch.arange(24).reshape(4, 6)
print("原始张量 A (4x6):\n", A)
print("形状 (Shape):", A.shape)
# 输出: torch.Size([4, 6])

原始张量 A (4x6):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
形状 (Shape): torch.Size([4, 6])


In [3]:
A.reshape(-1, 2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])

In [8]:
A.reshape((-1, 6))

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])